services:
  neo4j-nginx:
    image: nginx:1.27
    container_name: neo4j-nginx
    restart: unless-stopped
    ports:
      - "1080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - neo4j-frontend
      - neo4j-backend
    networks:
      - neo4j-network

  neo4j-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        # API Keys (replace with your actual keys or endpoints)
        - OPENAI_API_KEY=http://100.108.2.57/vllm_qwen2.5
        - DIFFBOT_API_KEY=token-abc123
    volumes:
      - ./backend:/code
    container_name: neo4j-backend
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - neo4j-network

  neo4j-frontend:
    depends_on:
      - neo4j-backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Replace with your actual model names
        # LLM Models for Production (comma-separated)
        - VITE_LLM_MODELS_PROD=Qwen2.5-Coder-14B-Instruct,Gemma2-9B-Sealion-V3-Instruct
        # LLMs for selection (comma-separated)
        - VITE_LLMS=Qwen2.5-Coder-14B-Instruct,Gemma2-9B-Sealion-V3-Instruct
        # Authentication (set to true to skip auth for development)
        - VITE_SKIP_AUTH=true

    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: neo4j-frontend
    networks:
      - neo4j-network

  neo4j-browser:
    container_name: neo4j-browser
    restart: unless-stopped
    image: neo4j:latest
    ports:
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-P@ssw0rd}
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    networks:
      - neo4j-network

networks:
  neo4j-network:
    driver: bridge
